### PR TITLE
Move code to piece model

### PR DESCRIPTION
**Pull request by brantwellman**
- Move piece code was refactored and moved to the piece-model.
- Move test in for controller re-written

### CODE REVIEW

**Comment by nannigan** [comment]
Hi Brant,

Sorry for the confusion in the process of getting Travis going...
I think the Travis error on your pull request is due to your having a previous version of the .travis.yml file on your machine . Did you pull down the latest and greatest from git hub before making this pull request?
The version of .travis.yml on github master now is correct, so should interact  correctly with your pull request once you get it into your project.

Nan

**Comment by nannigan** [comment]
https://travis-ci.org/theFirehoseProject/chess

(also Brant despite the travis thing all that code was pretty impressive ;^)

Nan

**Comment by kenmazaika** [comment]
Some seriously awesome code! :)

**Comment by nannigan** [comment]
just to expand on the Travis explanation:

besides Brant’s cute avatar this is showing that jruby-19mode and jruby20mode in the .travis.yml file broke the build.
Once the builds work the out put is terminal output showing what’s happening or where the problem/s are.

N.

**Comment by kenmazaika** [comment]
Nan is the TravisCI pro.  Love it! :)

**Comment by bobbyali** [comment]
Update looks great. I like how the back end is getting nice and tidy now. : )

**Comment by brantwellman** [comment]
Woot woot! travis.yml file updated and everything passes!

**Comment by kenmazaika** [comment]
@brantwellman, looks like it can't be automatically merged into master, the button is disabled.  You should merge master, resolve the conflicts, so someone who reviews your code can press that merge button (it's disabled now).

**Comment by brantwellman** [comment]
The "greyed-out/disabled merge button of death"!

I'm on it.

**Comment by brantwellman** [comment]
Ok, conflicts have been resolved, but there are move-test errors. Let me look into these before anyone merges this branch.

**Comment by brantwellman** [comment]
I had to make changes to a few of the tests because of the changes Rehan made to the db and how we are dealing with the Pieces.

But we should be good to go now!

**Comment by bobbyali** [comment]
Ah yes, glad you spotted that Brant. : )

**Comment by bobbyali** [comment]
Hi Nan,

Good questions.

1. The pawn model checks both black and white pieces, but the way it's written makes it looks like it only checks black. The current code says:

```ruby
if color == "black"
  blah
else
  blah
end
```

but this is the same as the following code, just terser:

```ruby
if color == "black"
  blah
elsif color == "white"
  blah
end
```

2. "y_init" refers to the initial position of the pawn at the start of the move, not the initial position at the start of the game. Over the course of the game, the black pawns can move all the way down the board. The only position they can't occupy is the very top, (y = 7), and so I'm not checking for this. (Whereas in the second half of the if statement, for the white pieces, I am doing this.)

Does this help?

Rehan

**Comment by bobbyali** [comment]
BTW I'm happy to do a conference call sometime to go through exactly what's going on here, because there is quite a lot going on in this code.

**Comment by nannigan** [comment]
On Jan 5, 2015, at 1:51 PM, Rehan Ali <notifications@github.com> wrote:

> Hi Nan,
> 
> Good questions.
> 
> The pawn model checks both black and white pieces, but the way it's written makes it looks like it only checks black. The current code says:
> if color == "black"
>   blah
> else
>   blah
> end
> but this is the same as the following code, just terser:
> 
> if color == "black"
>   blah
> elsif color == "white"
>   blah
> end

yes, that makes sense.

> "y_init" refers to the initial position of the pawn at the start of the move, not the initial position at the start of the game.
OK, that helps, thanks.
> Over the course of the game, the black pawns can move all the way down the board. The only position they can't occupy is the very top, (y = 7), and so I'm not checking for this. (Whereas in the second half of the if statement, for the white pieces, I am doing this.)
> Does this help?
> 
> 

Yes, and I expect I’ll have other ?s down the line ;^)

thanks,

Nan

**Comment by nannigan** [comment]
Hi Rehan,

Another one, I see you used a pawn in your tests for obstruction and move validity logic in the game_test. Are we going to need (if we do the testing thing correctly) write tests in the game_test for each piece, as well as in the piece_test?

If not, why not?

(I think I’m replying to all here wanting Brant to see this too)

thanks!

Nan

**Comment by bobbyali** [comment]
Yes and no. We'll definitely need to write tests for move validity for
every piece. But we should be able to split up those tests into different
files, one for each piece type that's being tested. That could help make
the test code a bit cleaner.

However we don't necessarily have to test the obstruction logic with every
piece, since it's a piece-independent feature. I think the existing test
demonstrates that it works properly, and should be sufficient. (Open to
suggestions though if anyone thinks otherwise.)

All the best,

Rehan

**Comment by kenmazaika** [comment]
I think you're spot on, Rehan.

Cheers,
Ken

**Pull request merged**
