### PR TITLE
Added simple drag-and-drop piece moving

### PR DESCRIPTION
**Pull request by bobbyali**
Added very simple drag-and-drop feature for piece moving. Need to run "bundle install" after loading this update, as I've used an additional ruby gem.

Next steps are:
1. Write tests.
2. Add intelligence so that it can figure out whether a proposed move is valid.
3. Return it to its original position if piece gets dragged somewhere bad (e.g. off the board).
4. Might have to deal with cases when it's not clear which tile it's on?

### CODE REVIEW

**Comment by kenmazaika** [comment]
That was fast, Rehan! :)

**Comment by kenmazaika** [comment]
I might suggest we break off some next steps into GitHub issues.

Other thing I would propose:
* Remove the select page, since we no longer go there.

**Comment by nannigan** [comment]
:thumbsup:

**Comment by nannigan** [comment]
I must apologize, I pushed  to master in error…

The good news is that we got it(Firebase) basically wired-up.
The bad news is that Travis is not passing the build.

The error at the end of the Travis print out is:
The command "bundle exec rake assets:precompile" failed and exited with 1 during .
Is there a safe way to revert the remote master to the previous state? I’m thinking
 git revert HEAD
is that right?

thanks!

Nan=

**Comment by kenmazaika** [comment]
Unfortunately if you did it as part of multiple commits it may take a
number of different commands to revert the change safely or a few commands
to do it in a less than safe way, here's why <http://take.ms/jM32l>.
 "Breaking the build" happens and it's not the end of the world.  I would
say do this:

*First*, try to figure out how to get travis passing again on a branch
*Second,* add a pull request for that change
*Third, *in that pull request link up to each of the commits you pushed to
master accidentally.

Assuming getting master passing isn't time critical, that's the easiest way
to go about it without wiping out all of your changes of firebase and
having to re-do them (you could revert both commits by sha hash, but then
it is hard to re-get-your-stuff on a branch).

We can talk about the details about this weird git stuff on Monday.

Cheers,
Ken

**Pull request merged**
